-- ==========================================
-- 1. CATÁLOGOS Y SUS TRADUCCIONES
-- ==========================================

CREATE TABLE mundra_states (
  slug TEXT PRIMARY KEY,
  label TEXT NOT NULL -- Etiqueta por defecto (español)
);

CREATE TABLE mundra_state_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_slug TEXT NOT NULL REFERENCES mundra_states(slug) ON DELETE CASCADE,
  language_code TEXT NOT NULL,
  label TEXT NOT NULL,
  
  CONSTRAINT unique_mundra_state_trans UNIQUE (state_slug, language_code)
);

CREATE TABLE mundra_themes (
  slug TEXT PRIMARY KEY,
  label TEXT NOT NULL -- Etiqueta por defecto (español)
);

CREATE TABLE mundra_theme_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  theme_slug TEXT NOT NULL REFERENCES mundra_themes(slug) ON DELETE CASCADE,
  language_code TEXT NOT NULL,
  label TEXT NOT NULL,
  
  CONSTRAINT unique_mundra_theme_trans UNIQUE (theme_slug, language_code)
);

-- ==========================================
-- 2. TABLA PRINCIPAL DE TOURS (Datos neutros)
-- ==========================================

CREATE TABLE mundra_tours (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  state_slug TEXT REFERENCES mundra_states(slug) ON DELETE SET NULL,
  theme_slug TEXT REFERENCES mundra_themes(slug) ON DELETE SET NULL,
  duration_hours NUMERIC(4,1) NOT NULL DEFAULT 0,
  price NUMERIC(10,2) NOT NULL DEFAULT 0,
  image TEXT,
  rating NUMERIC(2,1) DEFAULT 0.0,
  reviews INT DEFAULT 0,
  featured BOOLEAN DEFAULT false
);

-- ==========================================
-- 3. TRADUCCIONES DE TOURS
-- ==========================================

CREATE TABLE mundra_tour_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tour_id TEXT NOT NULL REFERENCES mundra_tours(id) ON DELETE CASCADE,
  language_code TEXT NOT NULL,
  
  -- Campos Traducibles
  title TEXT NOT NULL,
  place TEXT,
  start_time TEXT,
  meeting_point TEXT,
  includes TEXT[] DEFAULT '{}',
  excludes TEXT[] DEFAULT '{}',
  highlights TEXT[] DEFAULT '{}',
  itinerary JSONB DEFAULT '[]'::jsonb,

  CONSTRAINT unique_mundra_tour_trans UNIQUE (tour_id, language_code)
);

-- Índice de alto rendimiento para filtros por idioma
CREATE INDEX idx_mundra_tour_trans_lang ON mundra_tour_translations (tour_id, language_code);